### ISSUE TITLE
"Assertion `bHasStageData' failed." after lengthy system travel

### ISSUE THREAD

**Issue by docwild** [pioneerspacesim/pioneer#2199]
This is reproducible on my 64bit linux.

Go to Mu Herculis [-4, 0, 1]
Travel to Hooper Station ( more than 3000 AU )
Wait

CTD with ```pioneer: SpaceStationType.cpp:141: bool GetPosOrient(const TMapBayIDMat&, int, double, const vector3d&, SpaceStationType::positionOrient_t&, const Ship*): Assertion `bHasStageData' failed.```

```
#0  0x00007ffff5177475 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff517a6f0 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff5170621 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000000000052fbe9 in GetPosOrient (bayMap=..., stage=<optimized out>, t=<optimized out>, from=..., outPosOrient=..., 
    ship=<error reading variable: Unhandled dwarf expression opcode 0xfa>) at SpaceStationType.cpp:141
#4  0x0000000000530228 in SpaceStationType::GetDockAnimPositionOrient (this=<optimized out>, port=<optimized out>, stage=1, t=<optimized out>, from=..., outPosOrient=..., 
    ship=<optimized out>) at SpaceStationType.cpp:181
#5  0x0000000000525c1a in SpaceStation::PositionDockedShip (this=this@entry=0x36a5f20, ship=0x4fbb810, port=port@entry=0) at SpaceStation.cpp:493
#6  0x00000000005267e0 in SpaceStation::TimeStepUpdate (this=0x36a5f20, timeStep=<optimized out>) at SpaceStation.cpp:562
#7  0x00000000005234b8 in Space::TimeStep (this=0xf57ed0, step=166.666672) at Space.cpp:765
#8  0x000000000044173a in Game::TimeStep (this=0xf13b10, step=<optimized out>) at Game.cpp:240
#9  0x00000000004bf8bd in Pi::MainLoop () at Pi.cpp:974
#10 0x00000000004c04ec in Pi::Start () at Pi.cpp:910
#11 0x000000000040f685 in main (argc=1, argv=<optimized out>) at main.cpp:58
```

This happens at different times and different distances traveled.

**Comment by impaktor** [comment]
> Hopefully fixed but no-ones had time to look at my fix and merge it in yet.

Haven't resurfaced since then...
