### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by dvolk** [pioneerspacesim/pioneer#3051]
This is a crash that happens if I switch to (focus) a different window before Pioneer loads into the main menu.

```
Loading took: 17903.282076 milliseconds
pioneer: ./../SmartPtr.h:28: T* SmartPtrBase<Derived, T>::operator->() const [with Derived = RefCountedPtr<UI::Widget>; T = UI::Widget]: Assertion `m_ptr' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff5bb3f79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5bb3f79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5bb7388 in __GI_abort () at abort.c:89
#2  0x00007ffff5bace36 in __assert_fail_base (fmt=0x7ffff5cfe718 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x6c664c "m_ptr", file=file@entry=0x6df638 "./../SmartPtr.h", 
    line=line@entry=28, 
    function=function@entry=0x706460 <_ZZNK12SmartPtrBaseI13RefCountedPtrIN2UI6WidgetEES2_EptEvE19__PRETTY_FUNCTION__> "T* SmartPtrBase<Derived, T>::operator->() const [with Derived = RefCountedPtr<UI::Widget>; T = UI::Widget]") at assert.c:92
#3  0x00007ffff5bacee2 in __GI___assert_fail (assertion=0x6c664c "m_ptr", file=0x6df638 "./../SmartPtr.h", line=28, 
    function=0x706460 <_ZZNK12SmartPtrBaseI13RefCountedPtrIN2UI6WidgetEES2_EptEvE19__PRETTY_FUNCTION__> "T* SmartPtrBase<Derived, T>::operator->() const [with Derived = RefCountedPtr<UI::Widget>; T = UI::Widget]") at assert.c:101
#4  0x000000000040ba20 in SmartPtrBase<RefCountedPtr<UI::Widget>, UI::Widget>::operator-> (this=<optimized out>) at ./../SmartPtr.h:28
#5  0x000000000062125d in operator-> (this=<optimized out>) at ./../RefCounted.h:17
#6  UI::EventDispatcher::Dispatch (this=0x1888520, event=...) at EventDispatcher.cpp:76
#7  0x0000000000621986 in UI::EventDispatcher::DispatchSDLEvent (this=0x1888520, event=...) at EventDispatcher.cpp:43
#8  0x00000000004c060f in DispatchSDLEvent (event=..., this=<optimized out>) at ./ui/Context.h:131
#9  Pi::Start () at Pi.cpp:1050
#10 0x000000000040e869 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:128
```

**Comment by impaktor** [comment]
I wonder if the blame is on SDL, Pioneer, or i3?

**Comment by The-EG** [comment]
I don't think this is still relevant after 6 years, I imagine multiple changes to SDL, i3 and Pioneer have occurred. If it's still happening, we can reopen it.
