### ISSUE TITLE
Strange crash with new script

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3871]
This may not be the right place - but I don't know where to put this info and seek help...

While testing some new scripts of mine for permanent entities/corporations I was getting a bizarre crash every time I hyperjump. The problem is - from the gdb trace it does not even look like the crash is caused by any of my scripts. Does anyone have a clue where I need to look to debug? This is the gdb trace:

#0  0x00007ffff530f0c7 in raise () from /lib64/libc.so.6
#1  0x00007ffff5310478 in abort () from /lib64/libc.so.6
#2  0x00007ffff5308146 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff53081f2 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000040bdda in SmartPtrBase<RefCountedPtr<StarSystem>, StarSystem>::operator-> (this=<optimized out>) at SmartPtr.h:28
#5  0x00000000004c6285 in SmartPtrBase<RefCountedPtr<StarSystem>, StarSystem>::operator-> (this=<optimized out>) at LuaSpace.cpp:590
#6  l_space_get_body (l=<optimized out>) at LuaSpace.cpp:582
#7  0x000000000074ce05 in luaD_precall (L=L@entry=0x173ae90, func=<optimized out>, func@entry=0xe707980, nresults=nresults@entry=-1) at ldo.c:318
#8  0x000000000075a2e4 in luaV_execute (L=L@entry=0x173ae90) at lvm.c:709
#9  0x000000000074d429 in luaD_call (L=0x173ae90, func=<optimized out>, nResults=<optimized out>, allowyield=0) at ldo.c:395
#10 0x000000000074c619 in luaD_rawrunprotected (L=0x173ae90, f=0x7451f0 <f_call>, ud=0x7fffffffce50) at ldo.c:131
#11 0x000000000074d7f1 in luaD_pcall (L=L@entry=0x173ae90, func=func@entry=0x7451f0 <f_call>, u=u@entry=0x7fffffffce50, old_top=128, ef=<optimized out>)
    at ldo.c:595
#12 0x0000000000749ff5 in lua_pcallk (L=0x173ae90, nargs=0, nresults=1, errfunc=<optimized out>, ctx=0, k=<optimized out>) at lapi.c:949
#13 0x00000000004cbdfc in pi_lua_protected_call (L=L@entry=0x173ae90, nargs=nargs@entry=0, nresults=nresults@entry=1) at LuaUtils.cpp:559
#14 0x00000000004cb14d in LuaTimer::Tick (this=<optimized out>) at LuaTimer.cpp:44
#15 0x000000000057609a in Space::TimeStep (this=0x1945de80, step=step@entry=0.0166666675) at Space.cpp:963
#16 0x000000000045aa51 in Game::TimeStep (this=0x112db2d0, step=step@entry=0.0166666675) at Game.cpp:248
#17 0x00000000004efde0 in Pi::MainLoop () at Pi.cpp:1341
#18 0x00000000004f0f61 in Pi::Start () at Pi.cpp:1256
#19 0x00000000004135c9 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:130

### Steps to reproduce

__My pioneer version (and OS):__

**Comment by clausimu** [comment]
Had a discussion with ecraven on IRC about this. Apparently, I am trying to get a systempath during hyperjump (which is not possible). I know where to debug at least. Closing.
