### ISSUE TITLE
SIGSEGV, Segmentation fault on hyperspace while in external camera view

### ISSUE THREAD

**Issue by jpwgarrison** [pioneerspacesim/pioneer#4997]
### Observed behaviour
Core dump/SIGSEGV at hyperspace jump to Sirius

### Expected behaviour
Successful jump

### Steps to reproduce
Start new game on Mars, fly to Olympus Mons, attempt to jump to Sirius

__My pioneer version (and OS):__
Ubuntu 20.04, commit 1195d178db1719d041ed3e4d8c2720efdcb8ee49 (HEAD -> master, origin/master, origin/HEAD)

```
Reading symbols from build/pioneer...
[New LWP 287275]
[New LWP 287452]
[New LWP 287383]
[New LWP 287385]
[New LWP 287384]
[New LWP 287453]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `build/pioneer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055c44a0a39d3 in CollisionSpace::TraceRay (this=0x55c476a611a0, start=..., dir=..., len=200, c=c@entry=0x7fff4c9c0740, ignore=0x55c47cafeda0) at /home/redacted/pioneer/src/collider/CollisionSpace.cpp:311
311		vector3d invDir(1.0 / dir.x, 1.0 / dir.y, 1.0 / dir.z);
[Current thread is 1 (Thread 0x7f40adf6e800 (LWP 287275))]
(gdb)

**Comment by jpwgarrison** [comment]
I tried to repro without the stop at Olympus Mons and it did not segfault.
I tried again (flying to Olympus Mons first) and it repro'd again:

```
Started hyperspacing...

Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
0x00005555556b69d3 in CollisionSpace::TraceRay (this=0x555587a55e20, start=..., dir=..., len=200, c=c@entry=0x7fffffffd3c0, ignore=0x555587a3b850)
    at /home/jredacted/pioneer/src/collider/CollisionSpace.cpp:311
311		vector3d invDir(1.0 / dir.x, 1.0 / dir.y, 1.0 / dir.z);
(gdb) bt
#0  0x00005555556b69d3 in CollisionSpace::TraceRay (this=0x555587a55e20, start=..., dir=..., len=200, c=c@entry=0x7fffffffd3c0, ignore=0x555587a3b850)
    at /home/redacted/pioneer/src/collider/CollisionSpace.cpp:311
#1  0x0000555555756ddd in ExternalCameraController::Update (this=0x55558a429760) at /home/redacted/pioneer/src/vector3.h:253
#2  0x00005555556ae194 in WorldView::Update (this=0x555573eb08e0) at /home/redacted/pioneer/src/WorldView.cpp:199
#3  0x000055555562c9f6 in GameLoop::Update (this=0x555555ba94e0, deltaTime=0.0241221543) at /home/redacted/pioneer/src/Pi.h:183
#4  0x000055555599315d in Application::Run (this=0x555555ba9260) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#5  0x00005555555f77bc in main (argc=<optimized out>, argv=<optimized out>) at /home/redacted/pioneer/src/Pi.h:143
(gdb)

**Comment by The-EG** [comment]
> \<sturnclaw\> I have a feeling this bug is the external camera trying to query a collision space that doesn't exist because we're in hyperspace

That would definitely appear to be the case. I can reproduce this, but only in external view mode. Internal and sidereal don't crash.
