### ISSUE TITLE
Segfault on master

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5328]
When starting a new game (New Hope), it crashes when clicking the button, from Main Menu:
```
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
SystemView::ResetViewpoint (this=this@entry=0x55555d261ec0) at /home/me/usr/src/pioneer/src/SystemView.cpp:134
134		m_atlasViewW = height * m_renderer->GetDisplayAspect();
(gdb) bt
#0  SystemView::ResetViewpoint (this=this@entry=0x55555d261ec0) at /home/me/usr/src/pioneer/src/SystemView.cpp:134
#1  0x00005555557c38f9 in SystemView::SystemView (this=this@entry=0x55555d261ec0, game=game@entry=0x55555a83fd40) at /home/me/usr/src/pioneer/src/SystemView.cpp:96
#2  0x0000555555751a71 in Game::Views::Init (this=0x55555cf7b310, game=0x55555a83fd40) at /home/me/usr/src/pioneer/src/Game.cpp:761
#3  0x000055555575210c in Game::CreateViews (this=this@entry=0x55555a83fd40) at /usr/include/c++/11.1.0/bits/unique_ptr.h:173
#4  0x00005555557526cc in Game::Game (this=this@entry=0x55555a83fd40, path=..., startDateTime=startDateTime@entry=696113870) at /home/me/usr/src/pioneer/src/Game.cpp:87
#5  0x000055555585e56b in l_game_start_game (l=0x555556465a40) at /home/me/usr/src/pioneer/src/lua/LuaGame.cpp:71
#6  0x00005555558ae4de in luaD_precall (L=L@entry=0x555556465a40, func=<optimized out>, func@entry=0x5555566f8850, nresults=nresults@entry=0)
    at /home/me/usr/src/pioneer/contrib/lua/src/ldo.c:318
#7  0x00005555558bd18d in luaV_execute (L=L@entry=0x555556465a40) at /home/me/usr/src/pioneer/contrib/lua/src/lvm.c:709
#8  0x00005555558ae868 in luaD_call (L=0x555556465a40, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>)
    at /home/me/usr/src/pioneer/contrib/lua/src/ldo.c:395
#9  0x00005555558ade1c in luaD_rawrunprotected (L=L@entry=0x555556465a40, f=f@entry=0x5555558a4ea0 <f_call>, ud=ud@entry=0x7fffffffd7c0)
    at /home/me/usr/src/pioneer/contrib/lua/src/ldo.c:131
#10 0x00005555558aea9f in luaD_pcall (L=L@entry=0x555556465a40, func=func@entry=0x5555558a4ea0 <f_call>, u=u@entry=0x7fffffffd7c0, old_top=304, ef=<optimized out>)
    at /home/me/usr/src/pioneer/contrib/lua/src/ldo.c:595
#11 0x00005555558a76b7 in lua_pcallk (L=0x555556465a40, nargs=<optimized out>, nresults=1, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>)
    at /home/me/usr/src/pioneer/contrib/lua/src/lapi.c:949
#12 0x00005555558a3f42 in pi_lua_protected_call (L=L@entry=0x555556465a40, nargs=nargs@entry=1, nresults=nresults@entry=1)
    at /home/me/usr/src/pioneer/src/lua/core/Sandbox.cpp:177
#13 0x00005555556be7ba in LuaTable::Call<bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double> (key="mainMenu", this=0x7fffffffd870)
    at /home/me/usr/src/pioneer/src/lua/LuaTable.h:402
#14 PiGui::RunHandler (delta=0.016766570508480072, handler="mainMenu") at /home/me/usr/src/pioneer/src/pigui/LuaPiGui.cpp:85
#15 0x00005555555f9c5f in MainMenu::Update (this=0x555555b8cff0, deltaTime=0.0167665705) at /usr/include/c++/11.1.0/bits/char_traits.h:329
#16 0x0000555555979d57 in Application::Run (this=0x555555b8cd80) at /home/me/usr/src/pioneer/src/core/Application.cpp:187
#17 0x00005555555c8e26 in main (argc=<optimized out>, argv=<optimized out>) at /home/me/usr/src/pioneer/src/Pi.h:147
```
I'm on 90a1c4c74c0204059287dc1cd0ce6885cb4da954

**Comment by nozmajner** [comment]
I'm not sure it is the same, but todays master (2021 01 21) crashes randomly on a new game. Can't give an output.txt yet, because Windows does not allow built Pioneer to write in Documents for some reason.
