### ISSUE TITLE
CTD when clicking on "Switch to Sector Map" button

### ISSUE THREAD

**Issue by HelloMiko** [pioneerspacesim/pioneer#5349]
### Observed behaviour
Load my game
Immediately upon loading I am leaving an orbital station (ie. Requested undock, then saved the game)
A hyperspace jump is already plotted
Clicking the "Switch to Sector Map" button at the top results in a crash to desktop
Reloaded the game
Made the jump without looking at the Sector Map - which was successful
Clicking the "Switch to Sector Map" button in the next system still results in a crash to desktop

### Expected behaviour
"Switch to Sector Map" button displays Sector Map

### Steps to reproduce
Can I attach my save here? I shared it on the #technical_support channel of the "Beyond the Frontier" discord on 20/02/2022 at 18:23 UK time - EDIT: Found out I can attach my save here :)
Clicking the sector map results in a CTD.

__My pioneer version (and OS):__ 20220218 (Win 10)

[20220218 CTD when clicking sector map.zip](https://github.com/pioneerspacesim/pioneer/files/8104672/20220218.CTD.when.clicking.sector.map.zip)

**Comment by loveaabb** [comment]
The same thing happened to me... On version 20220218 too
Here's my saved game
[Aaaaa.zip](https://github.com/pioneerspacesim/pioneer/files/8237965/Aaaaa.zip)

**Comment by impaktor** [comment]
Confirmed. Got backtrace:
```
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
0x000055555560dfc4 in SectorView::FactionLabel::FactionLabel (path=..., radius=15, name="Commonwealth of Independent Worlds", home="Epsilon Eridani", color=<synthetic pointer>..., pos=..., host=..., this=0x55555bd066a0) at /home/karlf/usr/src/pioneer/src/SectorView.cpp:194
194			homePos(pos.x + radius + host.gap, pos.y - host.factionHomeFont->FontSize - host.gap),
(gdb) bt
#0  0x000055555560dfc4 in SectorView::FactionLabel::FactionLabel (path=..., radius=15, name="Commonwealth of Independent Worlds", home="Epsilon Eridani", 
    color=<synthetic pointer>..., pos=..., host=..., this=0x55555bd066a0) at /home/karlf/usr/src/pioneer/src/SectorView.cpp:194
#1  std::make_unique<SectorView::FactionLabel, SectorView::Labels&, vector3<float>, Color4ub&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, float, SystemPath> () at /usr/include/c++/11.1.0/bits/unique_ptr.h:962
#2  SectorView::PutFactionLabels (this=0x55555d4f08b0, origin=...) at /home/karlf/usr/src/pioneer/src/SectorView.cpp:952
#3  0x00005555556110a8 in SectorView::DrawFarSectors (this=0x55555d4f08b0, modelview=...) at /home/karlf/usr/src/pioneer/src/SectorView.cpp:1473
#4  0x0000555555611f9d in SectorView::Draw3D (this=0x55555d4f08b0) at /home/karlf/usr/src/pioneer/src/SectorView.cpp:699
#5  0x00005555555facca in GameLoop::Update (this=0x555555b8cc10, deltaTime=0.0229656454) at /home/karlf/usr/src/pioneer/src/Pi.cpp:996
#6  0x0000555555979cb7 in Application::Run (this=0x555555b8c930) at /home/karlf/usr/src/pioneer/src/core/Application.cpp:187
#7  0x00005555555c8076 in main (argc=<optimized out>, argv=<optimized out>) at /home/karlf/usr/src/pioneer/src/Pi.h:147
```

**Comment by slavicphilosofr** [comment]
I am experiencing the same bug with Pioneer version 20220203 (9c06c9f) on Windows 11. Attached I have a zip file containing the save file in question (named "save6") along with my output.txt and opengl.txt files generated after the bug.
[bug.zip](https://github.com/pioneerspacesim/pioneer/files/8258607/bug.zip)

**Comment by Gliese852** [comment]
@HelloMiko @loveaabb The problem was that in that save the sector map was in a state of displaying faction labels. It seems that there is no workaround for this, you need to install the fixed version of the game, otherwise the sector map will never open again in this save.
Apparently this build should contain a fix:
https://github.com/pioneerspacesim/pioneer/suites/5723960031/artifacts/189257875

**Comment by DarioTD** [comment]
I have a similar problem when I click on "Switch to Sector Map" while hyperspacing.
Idk If it is related
```
Started hyperspacing...

Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
l_sbody_attr_physics_body (l=<optimized out>) at /home/runner/work/pioneer/pioneer/src/lua/LuaSystemBody.cpp:696
696     in /home/runner/work/pioneer/pioneer/src/lua/LuaSystemBody.cpp
(gdb) bt
#0  l_sbody_attr_physics_body (l=<optimized out>) at /home/runner/work/pioneer/pioneer/src/lua/LuaSystemBody.cpp:696
#1  0x00005555558cbf62 in luaD_precall (L=L@entry=0x5555669185c0, func=<optimized out>, nresults=<optimized out>)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:318
#2  0x00005555558cc256 in luaD_call (L=0x5555669185c0, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:394
#3  0x00005555558cb824 in luaD_rawrunprotected (L=L@entry=0x5555669185c0, f=f@entry=0x5555558c3dd0 <f_call>, ud=ud@entry=0x7fffffffd860)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:131
#4  0x00005555558cc4d3 in luaD_pcall (L=L@entry=0x5555669185c0, func=func@entry=0x5555558c3dd0 <f_call>, u=u@entry=0x7fffffffd860, old_top=1136,
    ef=<optimized out>) at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:595
#5  0x00005555558c544b in lua_pcallk (L=L@entry=0x5555669185c0, nargs=nargs@entry=1, nresults=nresults@entry=1, errfunc=errfunc@entry=6,
    ctx=ctx@entry=0, k=k@entry=0x0) at /home/runner/work/pioneer/pioneer/contrib/lua/src/lapi.c:949
#6  0x00005555558c2e86 in pi_lua_protected_call (L=L@entry=0x5555669185c0, nargs=nargs@entry=1, nresults=nresults@entry=1)
    at /home/runner/work/pioneer/pioneer/src/lua/core/Sandbox.cpp:177
#7  0x00005555558865af in get_method_or_attr (l=0x5555669185c0) at /home/runner/work/pioneer/pioneer/src/lua/LuaMetaType.cpp:76
#8  get_method_or_attr (l=0x5555669185c0) at /home/runner/work/pioneer/pioneer/src/lua/LuaMetaType.cpp:63
#9  0x0000555555886cd9 in l_index (l=0x5555669185c0) at /home/runner/work/pioneer/pioneer/src/lua/LuaMetaType.cpp:133
#10 0x00005555558cbf62 in luaD_precall (L=L@entry=0x5555669185c0, func=<optimized out>, nresults=<optimized out>)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:318
#11 0x00005555558cc278 in luaD_call (L=0x5555669185c0, func=<optimized out>, nResults=nResults@entry=1, allowyield=<optimized out>)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:394
#12 0x00005555558d90e4 in callTM (L=L@entry=0x5555669185c0, p3=0x55556e1bf6d0, hasres=1, p2=<optimized out>, p2=<optimized out>,
    p1=<optimized out>, p1=<optimized out>, f=<optimized out>, f=<optimized out>) at /home/runner/work/pioneer/pioneer/contrib/lua/src/lvm.c:102
#13 0x00005555558d93f3 in luaV_gettable (L=L@entry=0x5555669185c0, t=0x55556e1bf6c0, key=0x55556778eeb0, val=val@entry=0x55556e1bf6d0)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/lvm.c:127
#14 0x00005555558daa1e in luaV_execute (L=L@entry=0x5555669185c0) at /home/runner/work/pioneer/pioneer/contrib/lua/src/lvm.c:588
#15 0x00005555558cc290 in luaD_call (L=0x5555669185c0, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:395
#16 0x00005555558cb824 in luaD_rawrunprotected (L=L@entry=0x5555669185c0, f=f@entry=0x5555558c3dd0 <f_call>, ud=ud@entry=0x7fffffffdc70)
    at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:131
#17 0x00005555558cc4d3 in luaD_pcall (L=L@entry=0x5555669185c0, func=func@entry=0x5555558c3dd0 <f_call>, u=u@entry=0x7fffffffdc70, old_top=304,
    ef=<optimized out>) at /home/runner/work/pioneer/pioneer/contrib/lua/src/ldo.c:595
#18 0x00005555558c544b in lua_pcallk (L=L@entry=0x5555669185c0, nargs=nargs@entry=1, nresults=nresults@entry=1, errfunc=errfunc@entry=18,
    ctx=ctx@entry=0, k=k@entry=0x0) at /home/runner/work/pioneer/pioneer/contrib/lua/src/lapi.c:949
#19 0x00005555558c2e86 in pi_lua_protected_call (L=0x5555669185c0, nargs=nargs@entry=1, nresults=nresults@entry=1)
    at /home/runner/work/pioneer/pioneer/src/lua/core/Sandbox.cpp:177
#20 0x00005555556dd178 in LuaTable::Call<bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double> (
    key="system-view", this=0x7fffffffdd30) at /home/runner/work/pioneer/pioneer/src/lua/LuaPushPull.h:156
#21 PiGui::RunHandler (delta=0.016282670199871063, handler="system-view") at /home/runner/work/pioneer/pioneer/src/pigui/LuaPiGui.cpp:85
#22 0x00005555556f8c20 in PiGuiView::DrawPiGui (this=<optimized out>) at /home/runner/work/pioneer/pioneer/src/Pi.h:138
--Type <RET> for more, q to quit, c to continue without paging--c
#23 0x00005555556168ed in GameLoop::Update (this=0x5555668e81f0, deltaTime=0.0162826702) at /home/runner/work/pioneer/pioneer/src/Pi.cpp:1024
#24 0x000055555598807d in Application::Run (this=0x5555668e7f10) at /home/runner/work/pioneer/pioneer/src/core/Application.cpp:187
#25 0x00005555555e2291 in main (argc=<optimized out>, argv=<optimized out>) at /home/runner/work/pioneer/pioneer/src/Pi.h:147
```
