### ISSUE TITLE
SIGFPE if flying long enough

### ISSUE THREAD

**Issue by Mc-Pain** [pioneerspacesim/pioneer#5516]
### Observed behaviour
```Thread 1 "pioneer" received signal SIGFPE, Arithmetic exception.
0x000055555575f198 in vector3<double>::Normalized (this=<synthetic pointer>) at /home/mcpain/pioneer/src/vector3.h:127
127                     const T l = 1.0f / sqrt(x * x + y * y + z * z);
(gdb) print x
$1 = <optimized out>
(gdb) print y
$2 = <optimized out>
(gdb) print z
$3 = <optimized out>
(gdb) bt
#0  0x000055555575f198 in vector3<double>::Normalized (this=<synthetic pointer>) at /home/mcpain/pioneer/src/vector3.h:127
#1  Propulsion::AIFaceUpdir (this=0x55558bd17ef8, updir=..., av=av@entry=0) at /home/mcpain/pioneer/src/ship/Propulsion.cpp:396
#2  0x00005555556818bc in AICmdFlyTo::TimeStepUpdate (this=0x5555871d4f20) at /home/mcpain/pioneer/src/ShipAICmd.cpp:1141
#3  0x0000555555679ab7 in AICommand::ProcessChild (this=this@entry=0x5555885b2d60) at /home/mcpain/pioneer/src/ShipAICmd.cpp:87
#4  0x000055555567ce3a in AICmdDock::TimeStepUpdate (this=0x5555885b2d60) at /home/mcpain/pioneer/src/ShipAICmd.cpp:1246
#5  0x00005555557ed4f2 in Ship::AITimeStep (this=0x555595507420, timeStep=timeStep@entry=166.666672) at /home/mcpain/pioneer/src/Ship-AI.cpp:37
#6  0x0000555555761702 in ShipController::StaticUpdate (this=0x55557994d6c0, timeStep=166.666672) at /home/mcpain/pioneer/src/ship/ShipController.cpp:11
#7  0x0000555555670587 in Ship::StaticUpdate (this=0x555595507420, timeStep=166.666672) at /home/mcpain/pioneer/src/Ship.cpp:1215
#8  0x000055555568fa33 in Space::TimeStep (this=0x55555db1d800, step=step@entry=166.666672) at /home/mcpain/pioneer/src/Space.cpp:1042
#9  0x00005555557a4ae9 in Game::TimeStep (this=0x5555590e2460, step=166.666672) at /usr/include/c++/12/bits/unique_ptr.h:191
#10 0x000055555563ed92 in GameLoop::Update (this=0x555555be0e70, deltaTime=0.276787758) at /home/mcpain/pioneer/src/Pi.cpp:944
#11 0x00005555555f3c07 in Application::Run (this=0x555555be0c90) at /home/mcpain/pioneer/src/core/Application.cpp:192
#12 0x00005555555d5272 in main (argc=<optimized out>, argv=<optimized out>) at /home/mcpain/pioneer/src/Pi.h:145
```

### Expected behaviour
Pioneer doesn't crash

### Steps to reproduce
1. Start on Mars
2. Take off, remove landing gear
3. Engage vertical thrusters (accelerate away from Mars)
3. Request time warp 10000x
4. Wait until running out of fuel (repeat 10000x as needed)
5. Enjoy a one-way trip away from solar system
6. Eventually, the game crashes. Sometimes before ship runs out of fuel.

__My pioneer version (and OS):__
ALT Linux, e765fd8cf

**Comment by impaktor** [comment]
Note to self: So, this was from latest master.

**Comment by Mc-Pain** [comment]
Latest release is also affected

**Comment by Gliese852** [comment]
https://user-images.githubusercontent.com/18342621/222826856-8b79dc08-9d7c-4872-a5e1-e44d7f0b1f3c.mp4

Can't reproduce, is 14000 AU far enough?

**Comment by Gliese852** [comment]
It turned out that this is not related to flying a long distance from the system, it just happens in a very rare case, so you need to wait a long time. It was possible to synthetically reproduce this state using a lua-script, and with the given patch, SIGFPE does not occur.
