### ISSUE TITLE
StringTable::Erase() and StringTable::Reclaim() leak memory

### ISSUE THREAD

**Issue by hexagonrecursion** [pioneerspacesim/pioneer#5696]
### Observed behaviour

`StringTable::Erase()` appears to leak memory. I detected this by running `./build/unittest -tc=StringName -sc=Creation` under a memory leak detector. `StringTable::Reclaim()` also leaks because it uses `StringTable::Erase()`

### Expected behaviour

No memory leak.

### Steps to reproduce

1. Enable sanitizers when creating the build directory. **Note:** be aware that cmake does **not** change CXXFLAGS or LDFLAGS for an already populated build directory.

       CXXFLAGS="-fsanitize=address,pointer-compare,pointer-subtract,undefined" LDFLAGS="$CXXFLAGS" cmake -S . -B build-sanitize/

4. make -j2 -C build-sanitize/
5. ./build-sanitize/unittest -tc=StringName -sc=Creation

```
==4578==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7f3cbc3692ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x69813b in StringName::make_data(char const*, unsigned int, unsigned int) /home/cdda/git/pioneer/src/core/StringName.cpp:60

SUMMARY: AddressSanitizer: 26 byte(s) leaked in 1 allocation(s).
```

__My pioneer version (and OS):__ 97d7be673f2124f1b42aee956c4b3a6fc2129558 (and Fedora release 39)

### Notes

Memory is allocated here:

https://github.com/pioneerspacesim/pioneer/blob/97d7be673f2124f1b42aee956c4b3a6fc2129558/src/core/StringName.cpp#L56-L67

I *think* memory is leaked here:

https://github.com/pioneerspacesim/pioneer/blob/97d7be673f2124f1b42aee956c4b3a6fc2129558/src/core/StringName.cpp#L134-L154

Sanity check: you allocate memory via `std::malloc()`, but I see precisely 0 occurrences of "free" in StringName.h or in StringName.cpp

@Web-eWorks , [you wrote the code](https://github.com/pioneerspacesim/pioneer/commit/c1e479e81dba1c11c34f35c118de0f01babb10a2). The code is complicated. I am not sure I understand it. Can you confirm?

**Comment by Web-eWorks** [comment]
I believe your surmise to be correct. The StringTable maps interned string hashes to string data, which is stored in an equivalent manner to a C-style flexible array member (the StringName::StringData structure is used as a header for the allocated string character data). It does look like I missed a deletion of that string data when erasing a string from the table, though that *technically* leaves dangling references if erasing a string with a non-zero refcount (i.e. outside of Reclaim).

If interested in fixing this, the allocated string data should be freed in Reclaim() before calling Erase(), and the Erase method ideally made private to the class.

**Comment by hexagonrecursion** [comment]
No promises
