### ISSUE TITLE
Game crashes on hyperjump with star field density set to 0

### ISSUE THREAD

**Issue by Maks2103** [pioneerspacesim/pioneer#5880]
### Observed behaviour
With star field density parameter set to zero, game crashes whenever trying to hyperjump

### Expected behaviour
Hyperjump working as usual.

### Steps to reproduce
Load game with the "Density of the star field" parameter set to 0, try to jump to another system (for example, from Sol to Sirius)

### Latest bug-free version
Release from 03.02.2024

__My pioneer version (and OS):__
Pioneer: v10.07.2024, OS: Windows 10

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/16447683/output.txt)
Somewhat graphic-related, so here's this as well: [opengl.txt](https://github.com/user-attachments/files/16447728/opengl.txt)
As for the save - new game would do for testing

**Comment by impaktor** [comment]
```
Info: 0 clouds brought over
Info: Started hyperspacing...

Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
0x00005555557247cd in Background::Starfield::Draw (this=0x555569246170) at /home/karlf/usr/src/pioneer/src/Background.cpp:613
613				Graphics::VertexBuffer *buffer = m_animMesh->GetVertexBuffer();
(gdb) bt
#0  0x00005555557247cd in Background::Starfield::Draw (this=0x555569246170) at /home/karlf/usr/src/pioneer/src/Background.cpp:613
#1  0x0000555555736e93 in Camera::Draw (this=0x55555dcd6670, excludeBody=excludeBody@entry=0x0) at /home/karlf/usr/src/pioneer/src/Camera.cpp:290
#2  0x00005555557e2095 in WorldView::Draw3D (this=0x5555568712a0) at /usr/include/c++/14.1.1/bits/unique_ptr.h:193
#3  0x000055555561ad7a in GameLoop::Update (this=0x555555be3210, deltaTime=0.0167936012) at /home/karlf/usr/src/pioneer/src/Pi.cpp:1011
#4  0x00005555555ed4ef in Application::Run (this=0x555555be2fb0) at /home/karlf/usr/src/pioneer/src/core/Application.cpp:193
#5  0x00005555555e6504 in main (argc=<optimized out>, argv=<optimized out>) at /home/karlf/usr/src/pioneer/src/Pi.h:144

```
